algoritmo "TrocarValores"
// Função :
// Autor :
// Data : 15/03/2022
// Seção de Declarações 
var
a,b,c:inteiro
inicio
// Seção de Comandos 
escreval("digite seu valor de a: ")
leia(a)
escreval("digite seu valor de b: ")
leia(b)

c<-a
a<-b
b<-c

escreval("*************************")
escreval("*  O valor de a é: ",a,"  *")
escreval("*                       *")
escreval("*  O valor de b é: ",b,"  *")
escreval("*************************")
fimalgoritmo
